apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "webapp-color.labels" . }}
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "webapp-color.labels" . | nindent 4 }}
    spec:
      containers:
      - image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default "latest" }}
        name: {{ .Release.Name }}-pod
        env:
        - name: BG_COLOR
          value: {{ .Values.appConfig.bgColor | quote }}
        - name: TEXT_COLOR
          value: {{ .Values.appConfig.textColor | quote }}
        - name: MESSAGE
          value: {{ .Values.appConfig.message | quote }}